apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: provider3000-ingress
  labels:
    app: provider3000
    backstage.io/kubernetes-id: provider3000 
spec:
  rules:
    - host: api-provider3000-pacticipants-dev.empcbr.thoughtworks-labs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: provider3000
                port: 
                  number: 80
  tls:
  - hosts:
    - api-provider3000-pacticipants-dev.empcbr.thoughtworks-labs.net
    secretName: letencryptkey
---
apiVersion: v1
kind: Service
metadata:
  name: provider3000
  labels:
    app: provider3000
    backstage.io/kubernetes-id: provider3000
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: provider3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider3000
  labels:
    app: provider3000
    backstage.io/kubernetes-id: provider3000
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: provider3000
  template:
    metadata:
      labels:
        app: provider3000
    spec:
      containers:
      - name: provider3000
        image: 626109959667.dkr.ecr.us-east-1.amazonaws.com/provider3000:{image-tag}
        ports:
        - containerPort: 8080
